[tool.poetry]
name = "mall-be"
version = "0.1.0"
description = ""
authors = ["BiDuang <me@biduang.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = { extras = ["all"], version = "^0.115.5" }
rich = "^13.9.4"
concurrent-log-handler = "^0.9.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
